db:
  host: 192.168.88.200
  port: 3306
  db_type: mysql
  connect_type: pymysql
  user: root
  pass: root
  db_name: test

celery:
  broker: pyamqp://stock_user:stock_pass@192.168.88.200:32773/stock_host
  backend: redis://192.168.88.200:6379/2


url:
  #实时行情
  sina : http://hq.sinajs.cn/list=sh600900
  #分时数据
  sina2 : http://money.finance.sina.com.cn/quotes_service/api/json_v2.php/CN_MarketData.getKLineData?symbol=sz000001&scale=5&ma=5&datalen=1023
  #url : https://xueqiu.com/stock/forchartk/stocklist.json?symbol=SZ000651&period=1day&type=before&begin=1478620800000&end=1510126200000&_=1510126200000
  xueqiu: https://xueqiu.com/stock/forchartk/stocklist.json?symbol={}&period={}&type={}&begin={}&end={}&_={}
  xueqiu2: https://xueqiu.com/stock/forchartk/stocklist.json?symbol={}&period={}&type={}

cookies:
  xueqiu:
    xq_a_token : bcf5d7813a913c224d76139411eabe776fc47d38






