db:
  connect_type: pymysql
  type: mysql
  host: 192.168.88.200
  port: 3306
  username: xx
  password: xx
  db_name: test
  charset: utf-8

redis:
  host: 121.15.10.34
  port: 8912
  password: rt0755
  broker_db: 1
